DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    ID INT NOT NULL AUTO_INCREMENT
  , LOGIN VARCHAR(32) NOT NULL UNIQUE
  , EMAIL VARCHAR(32) NOT NULL UNIQUE
  , PASSWORD VARCHAR(32) NOT NULL
);

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
    ID INT NOT NULL AUTO_INCREMENT
  , FIRST_NAME VARCHAR(32) NOT NULL
  , LAST_NAME VARCHAR(32) NOT NULL
  , BIRTH_DATE DATE
  , NICKNAME VARCHAR(32)
  , PRIMARY KEY (ID)
);