INSERT INTO PERSON
  (FIRST_NAME, LAST_NAME, BIRTH_DATE, NICKNAME)
VALUES
  ('Vladimir', 'Bredihin', '1985-02-05', 'Nickname?');
INSERT INTO PERSON
(FIRST_NAME, LAST_NAME, BIRTH_DATE, NICKNAME)
VALUES
  ('Julia', 'Bredihina', '1986-06-11', 'Nickname?');